version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PASSWORD
        environment:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: myappdb
          DATABASE_USERNAME: postgres
          TEST_DATABASE: myappdb

      - image: cimg/postgres:latest
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myappdb
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Build and push to Dockerhub
          command: |
            docker build -t $IMAGE_NAME .
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest            


workflows:
  version: 2
  build-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
